# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainui.ui'
#
# Created: Mon Sep 16 16:00:27 2013
#      by: pyside-uic 0.2.14 running on PySide 1.1.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1157, 635)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtGui.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.co2Source = QtGui.QSlider(self.groupBox)
        self.co2Source.setOrientation(QtCore.Qt.Vertical)
        self.co2Source.setTickPosition(QtGui.QSlider.TicksBelow)
        self.co2Source.setObjectName("co2Source")
        self.verticalLayout.addWidget(self.co2Source)
        self.co2SourceLabel = QtGui.QLabel(self.groupBox)
        self.co2SourceLabel.setObjectName("co2SourceLabel")
        self.verticalLayout.addWidget(self.co2SourceLabel)
        self.co2SourceValue = QtGui.QLineEdit(self.groupBox)
        self.co2SourceValue.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.co2SourceValue.sizePolicy().hasHeightForWidth())
        self.co2SourceValue.setSizePolicy(sizePolicy)
        self.co2SourceValue.setObjectName("co2SourceValue")
        self.verticalLayout.addWidget(self.co2SourceValue)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.co2Sink = QtGui.QSlider(self.groupBox)
        self.co2Sink.setOrientation(QtCore.Qt.Vertical)
        self.co2Sink.setTickPosition(QtGui.QSlider.TicksBelow)
        self.co2Sink.setObjectName("co2Sink")
        self.verticalLayout_2.addWidget(self.co2Sink)
        self.co2SinkLabel = QtGui.QLabel(self.groupBox)
        self.co2SinkLabel.setObjectName("co2SinkLabel")
        self.verticalLayout_2.addWidget(self.co2SinkLabel)
        self.co2SinkValue = QtGui.QLineEdit(self.groupBox)
        self.co2SinkValue.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.co2SinkValue.sizePolicy().hasHeightForWidth())
        self.co2SinkValue.setSizePolicy(sizePolicy)
        self.co2SinkValue.setObjectName("co2SinkValue")
        self.verticalLayout_2.addWidget(self.co2SinkValue)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 1, 1, 1)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.protonSource = QtGui.QSlider(self.groupBox)
        self.protonSource.setOrientation(QtCore.Qt.Vertical)
        self.protonSource.setTickPosition(QtGui.QSlider.TicksBelow)
        self.protonSource.setObjectName("protonSource")
        self.verticalLayout_3.addWidget(self.protonSource)
        self.protonSourceLabel = QtGui.QLabel(self.groupBox)
        self.protonSourceLabel.setObjectName("protonSourceLabel")
        self.verticalLayout_3.addWidget(self.protonSourceLabel)
        self.protonSourceValue = QtGui.QLineEdit(self.groupBox)
        self.protonSourceValue.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.protonSourceValue.sizePolicy().hasHeightForWidth())
        self.protonSourceValue.setSizePolicy(sizePolicy)
        self.protonSourceValue.setObjectName("protonSourceValue")
        self.verticalLayout_3.addWidget(self.protonSourceValue)
        self.gridLayout.addLayout(self.verticalLayout_3, 0, 2, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.protonLevelPurge = QtGui.QPushButton(self.groupBox)
        self.protonLevelPurge.setObjectName("protonLevelPurge")
        self.horizontalLayout.addWidget(self.protonLevelPurge)
        self.protonPurgeAmount = QtGui.QLineEdit(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.protonPurgeAmount.sizePolicy().hasHeightForWidth())
        self.protonPurgeAmount.setSizePolicy(sizePolicy)
        self.protonPurgeAmount.setObjectName("protonPurgeAmount")
        self.horizontalLayout.addWidget(self.protonPurgeAmount)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 1, 3)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 2, 0, 1, 1)
        self.horizontalLayout_3.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.plotArea = MatplotlibWidget(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plotArea.sizePolicy().hasHeightForWidth())
        self.plotArea.setSizePolicy(sizePolicy)
        self.plotArea.setMinimumSize(QtCore.QSize(200, 100))
        self.plotArea.setObjectName("plotArea")
        self.verticalLayout_4.addWidget(self.plotArea)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.simulateButton = QtGui.QPushButton(self.groupBox_2)
        self.simulateButton.setMinimumSize(QtCore.QSize(80, 0))
        self.simulateButton.setObjectName("simulateButton")
        self.horizontalLayout_2.addWidget(self.simulateButton)
        self.resetButton = QtGui.QPushButton(self.groupBox_2)
        self.resetButton.setObjectName("resetButton")
        self.horizontalLayout_2.addWidget(self.resetButton)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.logText = QtGui.QPlainTextEdit(self.groupBox_2)
        self.logText.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logText.sizePolicy().hasHeightForWidth())
        self.logText.setSizePolicy(sizePolicy)
        self.logText.setObjectName("logText")
        self.verticalLayout_4.addWidget(self.logText)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)
        self.horizontalLayout_3.addWidget(self.groupBox_2)
        self.groupBox_3 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.widget = ZincWidget(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setMinimumSize(QtCore.QSize(200, 100))
        self.widget.setBaseSize(QtCore.QSize(400, 0))
        self.widget.setObjectName("widget")
        self.verticalLayout_6.addWidget(self.widget)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.verticalLayout_6.addItem(spacerItem3)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem4)
        self.horizontalLayout_3.addWidget(self.groupBox_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1157, 19))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "pH - Model Simulation", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Adjustments", None, QtGui.QApplication.UnicodeUTF8))
        self.co2SourceLabel.setText(QtGui.QApplication.translate("MainWindow", "CO2 source", None, QtGui.QApplication.UnicodeUTF8))
        self.co2SourceValue.setText(QtGui.QApplication.translate("MainWindow", "0.0", None, QtGui.QApplication.UnicodeUTF8))
        self.co2SinkLabel.setText(QtGui.QApplication.translate("MainWindow", "CO2 sink", None, QtGui.QApplication.UnicodeUTF8))
        self.co2SinkValue.setText(QtGui.QApplication.translate("MainWindow", "0.0", None, QtGui.QApplication.UnicodeUTF8))
        self.protonSourceLabel.setText(QtGui.QApplication.translate("MainWindow", "H+ source", None, QtGui.QApplication.UnicodeUTF8))
        self.protonSourceValue.setText(QtGui.QApplication.translate("MainWindow", "0.0", None, QtGui.QApplication.UnicodeUTF8))
        self.protonLevelPurge.setText(QtGui.QApplication.translate("MainWindow", "H+ purge", None, QtGui.QApplication.UnicodeUTF8))
        self.protonPurgeAmount.setText(QtGui.QApplication.translate("MainWindow", "0.1", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("MainWindow", "Results", None, QtGui.QApplication.UnicodeUTF8))
        self.simulateButton.setText(QtGui.QApplication.translate("MainWindow", "Simulate", None, QtGui.QApplication.UnicodeUTF8))
        self.resetButton.setText(QtGui.QApplication.translate("MainWindow", "Reset", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("MainWindow", "Visualisation", None, QtGui.QApplication.UnicodeUTF8))

from zincwidget import ZincWidget
from matplotlibwidget import MatplotlibWidget
